name: Autoupdate package

on:
  repository_dispatch:
    types: [library_release]

permissions: write-all

jobs:
  update-version-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Update package version
        env:
          PACKAGE: ${{github.event.client_payload.package}}
          VERSION: ${{github.event.client_payload.version}}
          AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm i ${{ env.PACKAGE }}@${{ env.VERSION }} -E

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        env:
          PACKAGE: ${{github.event.client_payload.package}}
          VERSION: ${{github.event.client_payload.version}}
        with:
          token: ${{secrets.PR_TOKEN}}
          labels: "automerge"
          commit-message: "Bump ${{ env.PACKAGE }} to ${{ env.VERSION }}"
          branch: "autoupdate/${{ env.PACKAGE }}-${{ env.VERSION }}"
          title: "autoupdate/Bump ${{  env.PACKAGE }} to ${{ env.VERSION }}"
          body: |
            This PR updates ${{ env.PACKAGE }} version to ${{ env.VERSION }} based on the dispatched event.

      - name: Get node_id from pull request
        id: get-node-id
        run: |
          RESPONSE=$(curl -sSL -H "Authorization: Bearer ${{ secrets.PR_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls/${{ env.PULL_REQUEST_NUMBER }}")
          NODE_ID=$(echo "$RESPONSE" | jq -r '.node_id')
          echo "::set-output name=node_id::$NODE_ID"

      - name: Enable auto merge for pull request
        env:
          PULL_REQUEST_NODE_ID: ${{ steps.get-node-id.outputs.node_id }}
        run: |
          echo ${{env.PULL_REQUEST_NODE_ID}}
          curl 'https://api.github.com/graphql' \
          -X POST \
          -H 'Authorization: Bearer ${{ secrets.PR_TOKEN }}' \
          -H 'content-type: application/json' \
          --data '{
            "query": "mutation { enablePullRequestAutoMerge(input: { pullRequestId: \"${{env.PULL_REQUEST_NODE_ID}}\" }) { pullRequest { number } } }"
          }'
