name: automerge

on:
  check_suite:
    types:
      - completed

jobs:
  automerge:
    name: automerge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: automerge
        env:
          GITHUB_TOKEN: ${{ secrets.PR_TOKEN }}
          MERGE_ERROR_FAIL: "true"
          PR_NUMBER: ${{ github.event.check_suite.pull_requests[0].number }}
          API_URL: "https://api.github.com/repos/luislongo/pr_receiver_b/pulls/${{ env.PR_NUMBER }}/merge"
        run: |
          echo "PR_NUMBER: $PR_NUMBER"
          echo "GITHUB_TOKEN: $GITHUB_TOKEN"
          echo "API_URL: $API_URL"
          echo "Running curl command..."
          curl -L \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -d '{"commit_title":"Expand enum","commit_message":"Add a new value to the merge_method enum"}' \
          "$API_URL"