name: Build and test

on:
  pull_request

jobs:
  build-and-test:
    name: Build and Test
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "16.14.2"
      
      - name: Install and build
        run: |
          npm i 
          npm run build
        env:
          AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  

