name: Receive Dispatched Event

on:
  repository_dispatch:
    types: [library_release]

permissions: write-all

jobs:
  update-version-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Update package version
        run: |
          npm i ${{github.event.client_payload.package}}
        env:
          AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{secrets.PR_TOKEN}}
          labels: "automerge"
          commit-message: "Bump ${{github.event.client_payload.package}} to ${{github.event.client_payload.version}}"
          branch: "autoupdate/${{github.event.client_payload.package}}-${{github.event.client_payload.version}}"
          title: "autoupdate/Bump ${{github.event.client_payload.package}} to ${{github.event.client_payload.version}}"
          body: |
            This PR updates ${{github.event.client_payload.package}} version to ${{github.event.client_payload.version}} based on the dispatched event.

      - name: Enables automerge in pull request
        run: |
          curl 'https://api.github.com/graphql' \
          -X POST \
          -H 'Authorization: Bearer ${{ secrets.PR_TOKEN }}' \
          -H 'content-type: application/json' \
          --data '{
            "query": "mutation { updatePullRequest(input: { pullRequestId: \"${{github.event.pull_request.id}}\", autoMergeEnable: true }) { pullRequest { id } } }"
          }'
