name: Receive Dispatched Event

on:
  repository_dispatch:
    types: [library_release]

permissions: write-all

jobs:
  update-version-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Update package version
        run: |
          npm i ${{github.event.client_payload.package}}
        env:
          AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{secrets.PR_TOKEN}}
          labels: "automerge"
          commit-message: "Bump ${{github.event.client_payload.package}} to ${{github.event.client_payload.version}}"
          branch: "autoupdate/${{github.event.client_payload.package}}-${{github.event.client_payload.version}}"
          title: "autoupdate/Bump ${{github.event.client_payload.package}} to ${{github.event.client_payload.version}}"
          body: |
            This PR updates ${{github.event.client_payload.package}} version to ${{github.event.client_payload.version}} based on the dispatched event.

      - name: Gets nodeId from PR numbert
        id: get-node-id
        run: |
          RESPONSE=$(curl -sSL -H "Authorization: Bearer ${{ secrets.PR_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls/${{ env.PULL_REQUEST_NUMBER }}")
          NODE_ID=$(echo "$RESPONSE" | jq -r '.node_id')
          echo "::set-output name=node_id::$NODE_ID"

      - name: Enable auto merge
        env:
          PULL_REQUEST_NODE_ID: ${{ steps.get-node-id.outputs.node_id }}
        run: |
          echo ${{env.PULL_REQUEST_NODE_ID}}
          curl 'https://api.github.com/graphql' \
          -X POST \
          -H 'Authorization: Bearer ${{ secrets.PR_TOKEN }}' \
          -H 'content-type: application/json' \
          --data '{
            "query": "mutation { enablePullRequestAutoMerge(input: { pullRequestId: \"${{env.PULL_REQUEST_NODE_ID}}\" }) { pullRequest { number } } }"
          }'
